<?xml version="1.0" encoding="UTF-8"?>
<testng-results total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-10-14T09:52:22Z" name="Default suite" finished-at="2023-10-14T09:52:22Z" duration-ms="17">
    <groups>
    </groups>
    <test started-at="2023-10-14T09:52:22Z" name="Default test" finished-at="2023-10-14T09:52:22Z" duration-ms="17">
      <class name="com.testcases.LoginTestcase">
        <test-method signature="myTest(java.lang.String, java.lang.String)[pri:0, instance:com.testcases.LoginTestcase@70ed52de]" started-at="2023-10-14T15:22:22Z" name="myTest" data-provider="readData" finished-at="2023-10-14T15:22:22Z" duration-ms="6" status="FAIL">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
The data provider is trying to pass 1 parameters but the method com.testcases.LoginTestcase#myTest takes 2 and TestNG is unable in inject a suitable object]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
The data provider is trying to pass 1 parameters but the method com.testcases.LoginTestcase#myTest takes 2 and TestNG is unable in inject a suitable object
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1361)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1225)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1359)
	... 17 more
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- myTest -->
      </class> <!-- com.testcases.LoginTestcase -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
